In [ ]:
# Create train / test split
# target encoding column brand 


# create new-auto with bouwjaar
bouwjaar = 2016 & new_ auto == 1 , good 
bouwjaar = 2015 & new_auto ==1, bad

In [1]:
import pandas as pd
from pandas import read_csv
import numpy as np
import random as rnd

# visualization
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')


# machine learning
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier

/opt/blue-python/3.5/lib/python3.5/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d

In [2]:
import string
PUNCT_TO_REMOVE = string.punctuation
def remove_punctuation(text):
    """custom function to remove the punctuation"""
    return text.translate(str.maketrans('', '', PUNCT_TO_REMOVE))


def text_pre_processing(text):
     #remove punctuation
    text = remove_punctuation(text)
    
    #lowercase & remove extra whitespace
    text = " ".join(text.lower().split()) 
    
    return text

In [3]:
data = pd.read_csv("car_extra.csv", index_col=0) 
data['src_ad_id'] = data['src_ad_id'].apply(lambda x: '{:.0f}'.format(x))
#data['emissie'].fillna(0, inplace=True)
# test preprocessing for model field to combine the same filed
data['model_pro']= data['model'].apply(lambda text: text_pre_processing(text))
data.head(5).T

,0,1,2,3,4
src_ad_id,1123009959,1018323670,1092848988,1151159673,1061622715
telclicks,1,0,0,3,0
bids,0,0,0,0,0
kleur,Zilver of Grijs,Zilver of Grijs,Zilver of Grijs,Zwart,Zilver of Grijs
carrosserie,Hatchback (3/5-deurs),Hatchback (3/5-deurs),Stationwagon,Sedan (2/4-deurs),MPV
kmstand,44958,25072,301409,194481,238101
days_live,31,31,31,31,9
photo_cnt,16,22,12,21,8
aantaldeuren,3,5,5,4,4
n_asq,0,1,0,1,0
bouwjaar,2013,2015,2004,2007,2002
emissie,105,122,132,314,178
energielabel,A,C,B,G,D
brand,VOLKSWAGEN,VOLKSWAGEN,OPEL,AUDI,RENAULT
l2,None,157,None,93,None
ad_start_dt,11/26/2016,11/11/2016,11/02/2016,11/11/2016,11/08/2016
vermogen,44,92,59,331,79
webclicks,2,4,3,13,0
model,UP,Golf,Astra,S8,Scenic
aantalstoelen,4,5,5,5,5
price,79500,189500,27500,199000,12500
group,A,A,B,A,A
date,2016-11-26,2016-11-11,2016-11-02,2016-11-11,2016-11-08
day_of_week,Saturday,Friday,Wednesday,Friday,Tuesday
auto_age,3,1,12,9,14
has_view,1,1,1,1,0
nr_view,3,5,3,17,0
nr_door,2_3door,4_5door,4_5door,4_5door,4_5door
nr_chair,4_5chair,4_5chair,4_5chair,4_5chair,4_5chair
nr_foto,13_23_foto,13_23_foto,8_12_foto,13_23_foto,8_12_foto
brand_nation,german,german,german,german,french
days_before_cyber_monday,2,17,26,17,20
has_kmstand,1,1,1,1,1
l2_modified,0,157,0,93,0
has_auto_driving,0,1,0,1,0
days_post,1_month,1_month,1_month,1_month,1_month
vermogen_group,<75pk,75-100pk,<75pk,>200pk,75-100pk
kmstand_pro,44958,25072,301409,194481,238101
new_auto,0,0,0,0,0
price_zero,0,0,0,0,0
model_pro,up,golf,astra,s8,scenic

In [4]:
df = data[data['group']== 'B']
target_list = ['src_ad_id', 'telclicks', 'bids','n_asq','webclicks',
               'group','l2','ad_start_dt','date','nr_view','model'
               ,'bouwjaar','aantaldeuren','aantalstoelen','photo_cnt','kmstand']

df = df.loc[:, ~df.columns.isin(target_list)]
df.isnull().sum()

kleur                       0
carrosserie                 0
days_live                   0
emissie                     0
energielabel                0
brand                       0
vermogen                    0
price                       0
day_of_week                 0
auto_age                    0
has_view                    0
nr_door                     0
nr_chair                    0
nr_foto                     0
brand_nation                0
days_before_cyber_monday    0
has_kmstand                 0
l2_modified                 0
has_auto_driving            0
days_post                   0
vermogen_group              0
kmstand_pro                 0
new_auto                    0
price_zero                  0
model_pro                   0
dtype: int64

In [5]:
df.columns

Index(['kleur', 'carrosserie', 'days_live', 'emissie', 'energielabel', 'brand',
       'vermogen', 'price', 'day_of_week', 'auto_age', 'has_view', 'nr_door',
       'nr_chair', 'nr_foto', 'brand_nation', 'days_before_cyber_monday',
       'has_kmstand', 'l2_modified', 'has_auto_driving', 'days_post',
       'vermogen_group', 'kmstand_pro', 'new_auto', 'price_zero', 'model_pro'],
      dtype='object')

In [6]:
df[df['emissie']==0]['energielabel'].value_counts()

?    10619
C      805
A      477
B      473
D      390
E      161
G      146
F       89
Name: energielabel, dtype: int64

In [7]:
#X = df.drop(['has_view'], axis=1).values
#y = df['has_view'].values

## direct set 1/3 for test data
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42, stratify = y)
#print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(64126, 24) (16032, 24) (64126,) (16032,)

In [8]:
msk = np.random.rand(len(df)) < 0.8
train_df = df[msk]
test_df = df[~msk]
print(train_df.shape, test_df.shape)

(64231, 25) (15927, 25)

In [9]:
train_df.head().T

,2,6,9,10,11
kleur,Zilver of Grijs,Rood,Zilver of Grijs,Zwart,Zilver of Grijs
carrosserie,Stationwagon,Cabriolet,?,MPV,Hatchback (3/5-deurs)
days_live,31,2,100,19,31
emissie,132,145,156,125,0
energielabel,B,C,B,C,?
brand,OPEL,RENAULT,FORD,VOLKSWAGEN,KIA
vermogen,59,97,103,103,47
price,27500,269500,64000,0,7490
day_of_week,Wednesday,Saturday,Saturday,Wednesday,Friday
auto_age,12,1,9,4,18
has_view,1,1,1,1,1
nr_door,4_5door,2_3door,4_5door,4_5door,4_5door
nr_chair,4_5chair,4_5chair,4_5chair,4_5chair,Unknown
nr_foto,8_12_foto,24_foto,8_12_foto,24_foto,8_12_foto
brand_nation,german,french,american,german,korean
days_before_cyber_monday,26,16,16,26,24
has_kmstand,1,1,1,1,1
l2_modified,0,0,112,0,119
has_auto_driving,0,0,1,0,1
days_post,1_month,1_week,always,1_month,1_month
vermogen_group,<75pk,75-100pk,101-125pk,101-125pk,<75pk
kmstand_pro,301409,3397,255417,109836,193773
new_auto,0,0,0,0,0
price_zero,0,0,0,1,0
model_pro,astra,megane,mondeo,touran,pride

## Target Encoding of Categorical Field
Categorical fields: <br>
    'kleur', 'carrosserie',  'energielabel', 'brand',
        'day_of_week', 'nr_door', 'nr_chair', 'nr_foto', 'brand_nation', 'has_kmstand', 'has_auto_driving', 'days_post',
       'vermogen_group',  'new_auto', 'price_zero', 'model_pro'
<br>
<br>
Numerical fields:<br>
 'days_live','emissie','vermogen', 'price','auto_age','days_before_cyber_monday','l2_modified','kmstand_pro',

In [16]:
col = 'kleur'
col_enc = 'kleur_enc'
target = 'has_view'
totalSum = train_df[col].map(train_df.groupby(col)[target].sum())
n_objects =  train_df[col].map(train_df.groupby(col)[target].count())
train_df[col_enc] = (totalSum - train_df[target]) / (n_objects - 1)

In [21]:
pd.unique(train_df[[col, col_enc]].values.ravel())

array(['Zilver of Grijs', 0.7391487174695136, 'Rood', 0.7405753968253969,
       'Zwart', 0.7660878447395302, 0.7661559414368403, 0.739195439891604,
       'Overige kleuren', 0.7501027538018906, 'Wit', 0.6536783042394015,
       'Blauw', 0.7783976146965471, 0.7783014331057035,
       0.6538341645885287, 'Groen', 0.8528600964851827,
       0.7408234126984127, '?', 0.9024390243902439, 0.7505137690094533,
       'Beige', 0.7572178477690289, 'Bruin', 0.6270691333982473,
       0.6280428432327166, 0.8532046864231564, 0.7585301837270341,
       0.9085365853658537], dtype=object)

In [18]:
len(encoded_feature)

64231

In [18]:
random_forest = RandomForestClassifier(n_estimators=100)
random_forest.fit(X_train, y_train)
y_pred = random_forest.predict(X_test)
random_forest.score(X_train, y_train)
acc_random_forest = round(random_forest.score(X_train, y_train) * 100, 2)
acc_random_forest

ValueError: could not convert string to float: 'Zwart'